name: quotage
description: An application to get quotes by reading the image through Machine Learning Kit.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_ml_vision:
  image_picker:
  http:
  swipedetector:
  animated_text_kit: ^1.1.1
  auto_size_text: ^0.2.2
  path_provider:
  rxdart:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/quotragelogo.png"



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/emptyframe.png
    - assets/quotecircle.png
    - assets/uploadasset.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Maven Pro
       fonts:
         - asset: font/MavenPro-Medium.ttf
         - asset: font/MavenPro-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: Montserrat Light
       fonts:
          - asset: font/MontserratLight.otf

     - family: Montserrat
       fonts:
          - asset: font/MontserratMedium.otf

     - family: Josefin Sans
       fonts:
          - asset: font/JosefinSans-SemiBold.ttf
            weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
